from smg.pyopencv import CVMat1b, CVMat1f, CVMat1i, CVMat3b


# CLASSES

class Depthmap:
	def __init__(self, width: int, height: int, fx: float, fy: float, cx: float, cy: float): ...

	def get_converged_count(self) -> int: ...
	def get_converged_percentage(self) -> float: ...
	def get_convergence_map(self) -> CVMat1i: ...
	def get_denoised_depthmap(self, lamb: float = 0.5, iterations: int = 200) -> CVMat1f: ...
	def get_depthmap(self) -> CVMat1f: ...
	def set_reference_image(self, img_curr: CVMat1b, t_curr_world: SE3f, min_depth: float, max_depth: float) -> bool: ...
	def update(self, img_curr: CVMat1b, t_curr_world: SE3f) -> None: ...

	@staticmethod
	def scale_mat(depthmap: CVMat1f) -> CVMat3b: ...

class PinholeCamera:
	fx: float
	fy: float
	cx: float
	cy: float

	def __init__(self, fx: float = 0.0, fy: float = 0.0, cx: float = 0.0, cy: float = 0.0): ...

class SE3f:
	def __init__(self, qw: float, qx: float, qy: float, qz: float, tx: float, ty: float, tz: float): ...
	def data(self, row: int, col: int) -> float: ...
	def inv(self) -> SE3f: ...

# ENUMERATIONS

class EConvergenceState(int):
	pass

UPDATE: EConvergenceState
CONVERGED: EConvergenceState
BORDER: EConvergenceState
DIVERGED: EConvergenceState
NO_MATCH: EConvergenceState
NOT_VISIBLE: EConvergenceState
