###################
# UseREMODE.cmake #
###################

SET(REMODE_ROOT_DIR "${PROJECT_SOURCE_DIR}/../rpg_open_remode" CACHE PATH "The REMODE root directory")

SET(REMODE_INCLUDE_DIR "${REMODE_ROOT_DIR}/include")

INCLUDE_DIRECTORIES(${REMODE_INCLUDE_DIR})

FIND_LIBRARY(REMODE_LIBRARY_DEBUG rpg_open_remode HINTS "${REMODE_ROOT_DIR}/lib/Debug")
FIND_LIBRARY(REMODE_CUDA_LIBRARY_DEBUG rpg_open_remode_cuda HINTS "${REMODE_ROOT_DIR}/lib/Debug")

FIND_LIBRARY(REMODE_LIBRARY_RELEASE rpg_open_remode HINTS "${REMODE_ROOT_DIR}/lib/Release")
FIND_LIBRARY(REMODE_CUDA_LIBRARY_RELEASE rpg_open_remode_cuda HINTS "${REMODE_ROOT_DIR}/lib/Release")

SET(REMODE_LIBRARY debug ${REMODE_LIBRARY_DEBUG} optimized ${REMODE_LIBRARY_RELEASE})
SET(REMODE_CUDA_LIBRARY debug ${REMODE_CUDA_LIBRARY_DEBUG} optimized ${REMODE_CUDA_LIBRARY_RELEASE})

SET(REMODE_LIBRARIES
${REMODE_LIBRARY}
${REMODE_CUDA_LIBRARY}
)
